site_name: Git Scripts Documentation
docs_dir: docs
nav:
  - Home: index.md
  - Installation: installation.md
  - CI/CD: cicd.md
  - Scripts:
    - Setup SSH: scripts/utils/setup-git-ssh.md
    - Initialize Repository: scripts/utils/init-repository.md
    - Commit and Push: scripts/utils/commit-push.md
    - Sync Remote: scripts/utils/sync-remote.md
    - Release Version: scripts/utils/release-version.md
    - Git Scripts Documentation: scripts/utils/documentation_scripts_git.md